// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9vm0uJh0PCfV1uapa_lKnCYclvbn1wSY',
    appId: '1:1044829806605:web:27ea72c7edf1ebd45fb544',
    messagingSenderId: '1044829806605',
    projectId: 'fir-auth-b2ed6',
    authDomain: 'fir-auth-b2ed6.firebaseapp.com',
    storageBucket: 'fir-auth-b2ed6.firebasestorage.app',
    measurementId: 'G-L5NC41C62G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDorWOs9f3RT3_O-j2s2tOkh34xnop_eUE',
    appId: '1:1044829806605:android:129c3a7c67c9e8735fb544',
    messagingSenderId: '1044829806605',
    projectId: 'fir-auth-b2ed6',
    storageBucket: 'fir-auth-b2ed6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJadfs_QWZzhYsRI-6orOFcWIakAeOd5o',
    appId: '1:1044829806605:ios:da38ca9e9987a83f5fb544',
    messagingSenderId: '1044829806605',
    projectId: 'fir-auth-b2ed6',
    storageBucket: 'fir-auth-b2ed6.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJadfs_QWZzhYsRI-6orOFcWIakAeOd5o',
    appId: '1:1044829806605:ios:da38ca9e9987a83f5fb544',
    messagingSenderId: '1044829806605',
    projectId: 'fir-auth-b2ed6',
    storageBucket: 'fir-auth-b2ed6.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9vm0uJh0PCfV1uapa_lKnCYclvbn1wSY',
    appId: '1:1044829806605:web:b2c595921563d26f5fb544',
    messagingSenderId: '1044829806605',
    projectId: 'fir-auth-b2ed6',
    authDomain: 'fir-auth-b2ed6.firebaseapp.com',
    storageBucket: 'fir-auth-b2ed6.firebasestorage.app',
    measurementId: 'G-SNH2FT1MX2',
  );
}
